name: Continuous Delivery

on:
  workflow_dispatch:
  push:
  release:
    types:
      - "released"

env:
  ASSET_NAME: inkscape-shalector-extension-${GITHUB_REF_NAME#v}.tar.xz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: |
          tar -cvJf ${ASSET_NAME} --directory src shalector
          ls .
      - name: Publish
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ env.ASSET_NAME }}
